-- Migration: Create user_habits and add habit_tracking to daily_logs
-- Run in Supabase SQL editor or via psql

-- 1) Create table user_habits
CREATE TABLE IF NOT EXISTS public.user_habits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL CHECK (type IN ('positive','negative')),
  is_custom boolean NOT NULL DEFAULT true,
  tolerance_threshold integer NOT NULL DEFAULT 0,
  current_streak integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  shields integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_habits_user_id ON public.user_habits(user_id);

-- 2) Add habit_tracking JSONB column to daily_logs
ALTER TABLE IF EXISTS public.daily_logs
  ADD COLUMN IF NOT EXISTS habit_tracking jsonb DEFAULT '[]'::jsonb;

-- Optional: backfill example (commented)
-- UPDATE public.daily_logs SET habit_tracking = '[]'::jsonb WHERE habit_tracking IS NULL;
